### ISSUE TITLE
Launch functionality with multiple CEs

### ISSUE THREAD

**Issue by ejseqera** [ejseqera/tw-py#14]
Need to figure out how we can handle launch method for pipelines with different CEs, and different workdirs/etc accordingly.

For example:
```
launch:
  - name: 'nf-core-rnaseq-url-launch'                  ## Remote launch
    pipeline: 'https://github.com/nf-core/rnaseq'
    profile: 'test'
    revision: '3.12.0'
    workspace: 'tw_cli_e2e_test/showcase'
    workspace-secrets: 'SENTIEON_LICENSE_BASE64'
    compute-envs:
      - name: 'seqera_aws_ireland_fusionv2_nvme'
        work-dir: 's3://seqeralabs-showcase'
        params:
          outdir: 's3://seqeralabs-showcase/nf-core-rnaseq/results'
        config: './pipelines/nextflow.config'
        pre-run: './pipelines/pre_run.txt'
      - name: 'seqera_gcp_finland'
        work-dir: 'gs://seqeralabs-showcase-eu-north-1'
        params-file: './pipelines/nf_core_rnaseq_params.yml'
  - name: 'nf-core-rnaseq-launchpad-launch'            ## Launchpad launch
    pipeline: 'nf-core-rnaseq'
    workspace: 'tw_cli_e2e_test/showcase'
    compute-envs:
      - name: 'seqera_aws_ireland_fusionv2_nvme'
        work-dir: 's3://seqeralabs-showcase'
        params:
          outdir: 's3://seqeralabs-showcase/nf-core-rnaseq/results'
        config: './pipelines/nextflow.config'
        pre-run: './pipelines/pre_run.txt'
      - name: 'seqera_gcp_finland'
        work-dir: 'gs://seqeralabs-showcase-eu-north-1'
        params-file: './pipelines/nf_core_rnaseq_params.yml'
```
Some things to think about:
- How do we handle running the launch method on every `pipeline` key with different options for `compute-envs`, `params-file`...
- We can parse the `work-dir` from CE if we output the JSON using the list method instead of explicitly specifying it here everytime
- If `url` is specified for `pipeline`, certain options will be required by default but if only the launchpad name is specified, than many options will be pre-configred. Can these be overriden via CLI? Need to test.
