### ISSUE TITLE
Unable to add a Dataset

### ISSUE THREAD

**Issue by drpatelh** [ejseqera/tw-py#44]
When I try to add the Dataset below:

```
datasets:
  - name: 'rnaseq_samples'
    description: 'Samplesheet to run the nf-core/rnaseq pipeline from end-to-end'
    header: true
    workspace: 'tw_cli_e2e_test/showcase'
    file-path: './datasets/rnaseq_samples.csv'
    overwrite: True
```

I get the following error:

```
DEBUG:root: Overwriting datasets
| 
| DEBUG:root: Running command: tw -o json datasets list
| 
| Missing required option: '--workspace=<workspace>'
| 
| Usage: tw datasets list [OPTIONS]
| 
| List all workspace datasets.
| 
| Options:
| * -w, --workspace=<workspace>   Workspace numeric identifier (TOWER_WORKSPACE_ID as default) or workspace reference as OrganizationName/WorkspaceName
|   -f, --filter=<filter>         Show only datasets which name contains the given word.
|   -h, --help                    Show this help message and exit.
|   -V, --version                 Print version information and exit.
| Traceback (most recent call last):
|   File "/opt/conda/bin/tw-pywrap", line 8, in <module>
|     sys.exit(main())
|   File "/opt/conda/lib/python3.10/site-packages/tw_pywrap/cli.py", line 101, in main
|     block_manager.handle_block(block, args)
|   File "/opt/conda/lib/python3.10/site-packages/tw_pywrap/cli.py", line 66, in handle_block
|     helper.handle_overwrite(self.tw, block, args["cmd_args"])
|   File "/opt/conda/lib/python3.10/site-packages/tw_pywrap/helper.py", line 381, in handle_overwrite
|     if utils.check_if_exists(json_data, operation["name_key"], tw_args["name"]):
|   File "/opt/conda/lib/python3.10/site-packages/tw_pywrap/utils.py", line 50, in check_if_exists
|     data = json.loads(json_data)
|   File "/opt/conda/lib/python3.10/json/__init__.py", line 346, in loads
|     return _default_decoder.decode(s)
|   File "/opt/conda/lib/python3.10/json/decoder.py", line 337, in decode
|     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
|   File "/opt/conda/lib/python3.10/json/decoder.py", line 355, in raw_decode
|     raise JSONDecodeError("Expecting value", s, err.value) from None
| json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ejseqera** [comment]
Fixed in #47 

Tested with:
```
datasets:
  - name: 'rnaseq_samples'
    description: 'Samplesheet to run the nf-core/rnaseq pipeline from end-to-end'
    header: true
    workspace: 'tw_cli_e2e/showcase'
    file-path: 'testing/datasets/rnaseq_samples.csv'
    overwrite: True
```
Trace:
```
DEBUG:root: Running command: tw -o json datasets list -w tw_cli_e2e/showcase

DEBUG:root: Running command: tw datasets add --header testing/datasets/rnaseq_samples.csv --name rnaseq_samples --workspace tw_cli_e2e/showcase --description 'Samplesheet to run the nf-core/rnaseq pipeline from end-to-end'
```
And with overwriting:
```
DEBUG:root: Overwriting datasets

Deleting generic datasets resource
DEBUG:root: Running command: tw -o json datasets list -w tw_cli_e2e/showcase

DEBUG:root: Running command: tw datasets delete --name rnaseq_samples --workspace tw_cli_e2e/showcase

DEBUG:root: Running command: tw datasets add --header testing/datasets/rnaseq_samples.csv --name rnaseq_samples --workspace tw_cli_e2e/showcase --description 'Samplesheet to run the nf-core/rnaseq pipeline from end-to-end'
```

Closing for now, let me know if the issue arises again.
